[package]
name = "sio"
version = "0.1.0"
edition = "2021"

[dependencies]
sio-portablecode = { path = "../sio-portablecode" }
sio-vm = { path = "../sio-vm" }
sio-compiler = { path = "../sio-compiler" }

pest = "2.1.0"
pest_derive = "2.1.0"
serde_json = "1.0"

[dev-dependencies]
regex = "1"
